/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assistant/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description Whether a model is configured. Says nothing else about it; the key never leaves the server.
         */
        get: operations["status_api_v1_assistant_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conflict-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_v1_conflict_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /** Send */
        post: operations["send_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draft */
        get: operations["draft_api_v1_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit */
        post: operations["commit_api_v1_drafts__draft_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard */
        post: operations["discard_api_v1_drafts__draft_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occurrences/{occurrence_id}/exception": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exception */
        post: operations["exception_api_v1_occurrences__occurrence_id__exception_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Places */
        get: operations["places_api_v1_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{occurrence_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_api_v1_reminders__occurrence_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_v1_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_api_v1_tasks__task_id__lifecycle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scene Weather */
        get: operations["scene_weather_api_v1_weather_scene_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssistantStatus */
        AssistantStatus: {
            /** Available */
            available: boolean;
        };
        /** CommitRequest */
        CommitRequest: {
            /** Conflict Acceptance */
            conflict_acceptance?: string | null;
            /** Digest */
            digest: string;
        };
        /** CommitResult */
        CommitResult: {
            /** Draft Id */
            draft_id: string;
            /** Event Id */
            event_id: string;
            /**
             * Status
             * @constant
             */
            status: "committed";
        };
        /** ConflictDecision */
        ConflictDecision: {
            /** Chosen Occurrence Id */
            chosen_occurrence_id: string;
            /** Missed Occurrence Ids */
            missed_occurrence_ids: string[];
            /** State Revision */
            state_revision: number;
        };
        /** ConflictDecisionRequest */
        ConflictDecisionRequest: {
            /** Chosen Occurrence Id */
            chosen_occurrence_id: string;
            /** Group */
            group: string[];
            /** State Revision */
            state_revision: number;
        };
        /** ConflictPair */
        ConflictPair: {
            /** Occurrence Id */
            occurrence_id: string;
            /** Slot */
            slot: string;
        };
        /** ConversationCreated */
        ConversationCreated: {
            /** Conversation Id */
            conversation_id: string;
            /** Revision */
            revision: number;
        };
        /** DiscardResult */
        DiscardResult: {
            /** Draft Id */
            draft_id: string;
            /**
             * Status
             * @constant
             */
            status: "discarded";
        };
        /** Draft */
        Draft: {
            /**
             * Anchor At
             * Format: date-time
             */
            anchor_at: string;
            /** Basis Phrase */
            basis_phrase: string;
            /** Committed Event Id */
            committed_event_id: string | null;
            /** Confirmable */
            confirmable: boolean;
            /** Conversation Id */
            conversation_id: string;
            /** Digest */
            digest: string;
            /** Draft Id */
            draft_id: string;
            /** Expired */
            expired: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            fields: components["schemas"]["DraftFields"];
            /**
             * Kind
             * @description create makes a new event; the others act on `target`. `fields` is the result after the change. The task_* kinds act on a flexible task, which has a deadline instead of a slot.
             * @enum {string}
             */
            kind: "create" | "change" | "cancel" | "excuse" | "task_create" | "task_change" | "task_cancel";
            /** Missing */
            missing: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "needs_clarification" | "ready" | "committed" | "superseded" | "discarded";
            /** Superseded By */
            superseded_by: string | null;
            /** Target */
            target: components["schemas"]["DraftTarget"] | components["schemas"]["TaskTarget"] | null;
        };
        /** DraftFields */
        DraftFields: {
            /**
             * Deadline
             * @description Flexible tasks only: when the user wants it done by.
             */
            deadline?: string | null;
            /** End At */
            end_at: string | null;
            /** Location */
            location: string | null;
            /**
             * Precision
             * @description date when the user named a day, instant when a clock time was named.
             */
            precision?: ("date" | "instant") | null;
            recurrence: components["schemas"]["Recurrence"] | null;
            /** Start At */
            start_at: string | null;
            /** Timezone */
            timezone: string | null;
            /** Title */
            title: string | null;
        };
        /**
         * DraftTarget
         * @description The saved instance a change draft acts on, as it was when the draft was made.
         */
        DraftTarget: {
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Event Id */
            event_id: string;
            /** Location */
            location: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /** Occurrence Version */
            occurrence_version: number;
            /** Original Slot */
            original_slot: string;
            /** Recurring */
            recurring: boolean;
            /**
             * Scope
             * @enum {string}
             */
            scope: "occurrence" | "series";
            /** Series Version */
            series_version: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Title */
            title: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Acceptance Token
             * @description CONFLICT_REVIEW_REQUIRED only: send back to save despite the overlap.
             */
            acceptance_token?: string | null;
            /** Code */
            code: string;
            /**
             * Conflicts
             * @description CONFLICT_REVIEW_REQUIRED only: candidate slot vs saved occurrence.
             */
            conflicts?: components["schemas"]["ConflictPair"][] | null;
            /** Message */
            message: string;
            /**
             * Superseded By
             * @description DRAFT_SUPERSEDED only.
             */
            superseded_by?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExceptionRequest */
        ExceptionRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** FlexibleTask */
        FlexibleTask: {
            /** Deadline */
            deadline: string | null;
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "planned" | "active" | "done";
            /** Overdue */
            overdue: boolean;
            /** Precision */
            precision: ("date" | "instant") | null;
            /** Task Id */
            task_id: string;
            /** Timezone */
            timezone: string;
            /** Title */
            title: string;
            /** Urgency */
            urgency: string;
            /** Version */
            version: number;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LifecycleRequest */
        LifecycleRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Target
             * @enum {string}
             */
            target: "planned" | "active" | "done";
        };
        /** LifecycleResult */
        LifecycleResult: {
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "planned" | "active" | "done";
            /** Task Id */
            task_id: string;
            /** Version */
            version: number;
        };
        /** Message */
        Message: {
            /** Action Results */
            action_results: components["schemas"]["ToolResult"][];
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Draft Id */
            draft_id: string | null;
            /** Message Id */
            message_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Sequence */
            sequence: number;
        };
        /** MessagePage */
        MessagePage: {
            /** Conversation Id */
            conversation_id: string;
            draft: components["schemas"]["Draft"] | null;
            /** Items */
            items: components["schemas"]["Message"][];
            /** Next Cursor */
            next_cursor: number | null;
            /**
             * Pending Client Message Id
             * @description An unfinished turn. Resend with this ID to resume it instead of starting another.
             */
            pending_client_message_id: string | null;
            /** Revision */
            revision: number;
        };
        /** Occurrence */
        Occurrence: {
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "scheduled" | "excused" | "missed" | "cancelled";
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Event Id */
            event_id: string;
            /** Location */
            location: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** Place */
        Place: {
            /** Admin1 */
            admin1: string | null;
            /** Country */
            country: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** PlaceList */
        PlaceList: {
            /** Items */
            items: components["schemas"]["Place"][];
        };
        /** Recurrence */
        Recurrence: {
            /** End Day Offset */
            end_day_offset: number;
            /** Ends On */
            ends_on: string;
            /** Fold Policy */
            fold_policy: ("earlier" | "later") | null;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "weekly";
            /** Gap Policy */
            gap_policy: "skip" | null;
            /** Local End */
            local_end: string;
            /** Local Start */
            local_start: string;
            /** Starts On */
            starts_on: string;
            /** Weekdays */
            weekdays: number[];
        };
        /** ReminderAck */
        ReminderAck: {
            /**
             * Acknowledged At
             * Format: date-time
             */
            acknowledged_at: string;
            /** Occurrence Id */
            occurrence_id: string;
            /** Occurrence Version */
            occurrence_version: number;
        };
        /** ReminderAckRequest */
        ReminderAckRequest: {
            /** Occurrence Version */
            occurrence_version: number;
        };
        /** SceneWeather */
        SceneWeather: {
            /** Attribution */
            attribution: string;
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "unavailable";
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Observed At */
            observed_at: string | null;
            /** Source */
            source: string;
            weather: components["schemas"]["SceneWeatherValues"] | null;
        };
        /** SceneWeatherValues */
        SceneWeatherValues: {
            /** Cloud */
            cloud: number;
            /**
             * Condition
             * @enum {string}
             */
            condition: "clear" | "partly_cloudy" | "overcast" | "fog" | "drizzle" | "rain" | "snow" | "thunderstorm";
            /** Fog */
            fog: number;
            /** Rain */
            rain: number;
            /** Snow */
            snow: number;
            /** Thunder */
            thunder: boolean;
            /** Wind */
            wind: number;
        };
        /** ScheduleState */
        ScheduleState: {
            /** Active */
            active: components["schemas"]["Occurrence"][];
            /** Conflicts */
            conflicts: string[][];
            /** Next Transition At */
            next_transition_at: string | null;
            /** Reminder Lead Seconds */
            reminder_lead_seconds: number;
            /**
             * Reminders
             * @description Scheduled instances starting within the lead window, not yet acknowledged at their current version.
             */
            reminders: components["schemas"]["Occurrence"][];
            /**
             * Server Now
             * Format: date-time
             */
            server_now: string;
            /** State Revision */
            state_revision: number;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Client Message Id */
            client_message_id: string;
            /** Content */
            content: string;
            /** Expected Revision */
            expected_revision: number;
            /** Timezone */
            timezone: string;
        };
        /** TaskList */
        TaskList: {
            /** Items */
            items: components["schemas"]["FlexibleTask"][];
            /**
             * Server Now
             * Format: date-time
             */
            server_now: string;
        };
        /**
         * TaskTarget
         * @description The saved flexible task a task_change / task_cancel draft acts on, as it was when made.
         */
        TaskTarget: {
            /** Deadline */
            deadline: string | null;
            /** Precision */
            precision: ("date" | "instant") | null;
            /** Task Id */
            task_id: string;
            /** Task Version */
            task_version: number;
            /** Title */
            title: string;
        };
        /** ToolResult */
        ToolResult: {
            /** Data */
            data: unknown;
            /** Draft Id */
            draft_id: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "rejected" | "clarify" | "unavailable";
        };
        /** TurnResult */
        TurnResult: {
            /** Answer */
            answer: string;
            /** Assistant Message Id */
            assistant_message_id: string;
            /** Conversation Id */
            conversation_id: string;
            draft: components["schemas"]["Draft"] | null;
            /** Revision */
            revision: number;
            /** Tool Results */
            tool_results: components["schemas"]["ToolResult"][];
            /** User Message Id */
            user_message_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_v1_assistant_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantStatus"];
                };
            };
        };
    };
    decide_api_v1_conflict_decisions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConflictDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictDecision"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationCreated"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    history_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    draft_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    commit_api_v1_drafts__draft_id__commit_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    discard_api_v1_drafts__draft_id__discard_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscardResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    exception_api_v1_occurrences__occurrence_id__exception_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                occurrence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExceptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Occurrence"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    places_api_v1_places_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceList"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    acknowledge_api_v1_reminders__occurrence_id__ack_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                occurrence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderAck"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    state_api_v1_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleState"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
        };
    };
    transition_api_v1_tasks__task_id__lifecycle_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifecycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    scene_weather_api_v1_weather_scene_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneWeather"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
