"""Contracts the application needs from the outside world. Adapters implement these."""

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from types import TracebackType
from typing import Any, Protocol, Self

from kairos.domain.conversation import Conversation, ConversationMessage, ConversationTurn
from kairos.domain.draft import Draft
from kairos.domain.events import EventSeries, OccurrenceState
from kairos.domain.tasks import FlexibleTask


class Clock(Protocol):
    def now(self) -> datetime: ...


class EventRepository(Protocol):
    def list_series(self, owner_id: str) -> list[EventSeries]: ...
    def add_series(self, series: EventSeries, created_at: datetime) -> None: ...
    def get_series(self, owner_id: str, event_id: str) -> EventSeries | None: ...
    def update_series(self, series: EventSeries, expected_version: int) -> None:
        """Replace content; raise VersionConflict if the stored version is not expected_version."""
        ...

    def delete_series(self, owner_id: str, event_id: str, expected_version: int) -> None:
        """Soft-delete; raise VersionConflict if the stored version is not expected_version."""
        ...


class OccurrenceStateRepository(Protocol):
    def states(self, owner_id: str) -> Mapping[str, OccurrenceState]: ...
    def save(self, owner_id: str, event_id: str, state: OccurrenceState, expected_version: int,
             updated_at: datetime) -> None:
        """Persist a new state; raise VersionConflict if the stored version is not expected_version."""
        ...


class FlexibleTaskRepository(Protocol):
    def list_tasks(self, owner_id: str) -> list[FlexibleTask]:
        """Every task the user still has, newest first. Deleted ones are left out."""
        ...

    def get_task(self, owner_id: str, task_id: str) -> FlexibleTask | None: ...
    def find_by_title(self, owner_id: str, normalized: str) -> list[FlexibleTask]:
        """Tasks whose normalized title matches, so "背单词" finds the one the user already has."""
        ...

    def add_task(self, task: FlexibleTask, created_at: datetime) -> None: ...
    def update_task(self, task: FlexibleTask, expected_version: int, updated_at: datetime) -> None:
        """Replace content; raise VersionConflict if the stored version is not expected_version."""
        ...

    def delete_task(self, owner_id: str, task_id: str, expected_version: int, at: datetime) -> None:
        """Soft-delete; raise VersionConflict if the stored version is not expected_version."""
        ...


class ReminderAckRepository(Protocol):
    def acknowledged(self, owner_id: str) -> set[tuple[str, int]]: ...
    def add(self, owner_id: str, occurrence_id: str, occurrence_version: int, at: datetime) -> None: ...


@dataclass(frozen=True)
class StoredResult:
    request_hash: str
    result: dict[str, Any]


class IdempotencyStore(Protocol):
    def get(self, owner_id: str, operation: str, key: str) -> StoredResult | None: ...
    def put(self, owner_id: str, operation: str, key: str, stored: StoredResult, at: datetime) -> None: ...


class AuditLog(Protocol):
    def record(self, owner_id: str, operation: str, subject_id: str, at: datetime) -> None: ...


class PendingTurnError(Exception):
    """Adapter-level signal: another turn of this conversation is still unfinished."""


class ConversationRepository(Protocol):
    def create(self, conversation: Conversation) -> None: ...
    def get(self, owner_id: str, conversation_id: str) -> Conversation | None: ...
    def bump(self, conversation_id: str, expected_revision: int, at: datetime) -> None:
        """Advance the revision; raise VersionConflict when it is not expected_revision."""
        ...


class MessageRepository(Protocol):
    def append(self, message: ConversationMessage) -> None: ...
    def get(self, owner_id: str, message_id: str) -> ConversationMessage | None: ...
    def after(self, owner_id: str, conversation_id: str, sequence: int, limit: int) -> list[ConversationMessage]: ...
    def tail(self, owner_id: str, conversation_id: str, limit: int) -> list[ConversationMessage]: ...
    def latest(self, owner_id: str, conversation_id: str) -> ConversationMessage | None: ...
    def draft_references(self, owner_id: str, conversation_id: str) -> list[str]:
        """Draft IDs referenced by this conversation's messages, newest first. Reading never runs tools."""
        ...


class TurnRepository(Protocol):
    def find(self, owner_id: str, conversation_id: str, client_message_id: str) -> ConversationTurn | None: ...
    def reserve(self, turn: ConversationTurn) -> None:
        """Insert a pending turn. Raise PendingTurnError when another turn is still pending."""
        ...

    def pending_client_message_id(self, owner_id: str, conversation_id: str) -> str | None: ...
    def complete(self, turn: ConversationTurn, assistant: ConversationMessage,
                 response: dict[str, Any]) -> None: ...


class DraftRepository(Protocol):
    def add(self, draft: Draft) -> None: ...
    def get(self, owner_id: str, draft_id: str) -> Draft | None: ...
    def find_for_source(self, owner_id: str, conversation_id: str, source_message_id: str,
                        statuses: tuple[str, ...]) -> Draft | None: ...

    def live(self, owner_id: str, conversation_id: str) -> Draft | None:
        """The newest draft of this conversation that is still open (ready or awaiting clarification)."""
        ...

    def newest(self, owner_id: str, conversation_id: str) -> Draft | None:
        """The newest draft of this conversation in any status, so a reload shows what became of it."""
        ...

    def supersede(self, owner_id: str, draft_id: str, successor_id: str, at: datetime) -> None: ...
    def commit_draft(self, owner_id: str, draft_id: str, digest: str, event_id: str, at: datetime) -> None:
        """Flip a `ready` draft to `committed`. Row-count guarded; raise VersionConflict otherwise."""
        ...

    def discard(self, owner_id: str, draft_id: str, at: datetime) -> None: ...


class UnitOfWork(Protocol):
    @property
    def events(self) -> EventRepository: ...
    @property
    def occurrences(self) -> OccurrenceStateRepository: ...
    @property
    def tasks(self) -> FlexibleTaskRepository: ...
    @property
    def acks(self) -> ReminderAckRepository: ...
    @property
    def idempotency(self) -> IdempotencyStore: ...
    @property
    def audit(self) -> AuditLog: ...
    @property
    def conversations(self) -> ConversationRepository: ...
    @property
    def messages(self) -> MessageRepository: ...
    @property
    def turns(self) -> TurnRepository: ...
    @property
    def drafts(self) -> DraftRepository: ...

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None,
                 tb: TracebackType | None) -> None: ...
    def commit(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self, *, write: bool) -> UnitOfWork: ...
